services:
  postgres:
    image: postgres:15
    container_name: hevo_postgres
    environment:
      POSTGRES_USER: hevo_user
      POSTGRES_PASSWORD: *****
      POSTGRES_DB: hevo_assessment
      TZ: "Asia/Kolkata"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: 
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "wal_sender_timeout=0" 

volumes:
  pgdata: